# Generated by Django 3.2.8 on 2021-10-18 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True)),
                ('enunciado', models.TextField()),
                ('alternativas_Multiplasescolhas', models.JSONField(blank=True, default={'A': ' ', 'B': ' ', 'C': ' ', 'D': ' ', 'E': ' '}, null=True)),
                ('alternativas_correta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('Certo', 'Certo'), ('Errado', 'Errado')], max_length=10)),
                ('disponivel', models.BooleanField(default=False)),
                ('banca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.banca')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.materia')),
            ],
        ),
    ]
